
// HEADER
export const TOGGLE_DISPLAY_MENU = 'TOGGLE_DISPLAY_MENU';
export const CLOSE_DISPLAY_MENU = 'CLOSE_DISPLAY_MENU';

// FILTER
export const RESET_FILTER = 'RESET_FILTER';
export const SELECT_FILTER = 'SELECT_FILTER';
export const SELECT_GENDER = 'SELECT_GENDER';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

// CART
export const CHECK_CART_HAS_ITEMS = 'CHECK_CART_HAS_ITEMS';

// MODAL
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// SEARCH
export const OPEN_SEARCH = 'OPEN_SEARCH';
export const CLOSE_SEARCH = 'CLOSE_SEARCH';
export const UPDATE_Q = 'UPDATE_Q';
